# Generated by Django 2.2.6 on 2019-11-23 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='rajat',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
