# Generated by Django 2.2.6 on 2019-11-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0002_sprint_rajat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='rajat',
        ),
    ]
