# Generated by Django 2.2.6 on 2019-11-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0004_auto_20191123_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='Not Yet Started', max_length=100),
        ),
    ]
