# Generated by Django 2.2.6 on 2019-11-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0005_auto_20191123_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(default='Ongoing', max_length=50),
        ),
    ]
