# Generated by Django 2.2.6 on 2019-11-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0006_sprint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='status',
        ),
    ]
