# Generated by Django 2.2.6 on 2019-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0007_remove_sprint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(default='Ongoing', max_length=50),
        ),
    ]
